<template>
    <div>
        <el-tabs v-model="activeName" @tab-click="handleClick">
                        <el-tab-pane label="选择领用资产" name="first">
                            <el-input placeholder="请输入内容" v-model="input5" class="input-with-select" style="width:50%;">
                                <el-button slot="append" icon="el-icon-search"></el-button>
                            </el-input>
                            <div style="height:20px;width:20px;"></div>
                            <!-- 表格展示开始 -->
                            <el-table
                                :data="tableData"
                                border ref="multipleTable"  tooltip-effect="dark" @selection-change="handleSelectionChange"
                                style="width: 100%">
                                <el-table-column
                                type="selection"
                                width="55" fixed>
                                </el-table-column>
                                <el-table-column
                                prop="bar_code"
                                label="资产条码"
                                width="150">
                                </el-table-column>
                                <el-table-column
                                prop="name"
                                label="资产名称"
                                width="120">
                                </el-table-column>
                                <el-table-column
                                prop="type_id"
                                label="资产类型"
                                width="120">
                                </el-table-column>
                                <el-table-column
                                prop="specification"
                                label="规格型号"
                                width="120">
                                </el-table-column>
                                <el-table-column
                                prop="sn"
                                label="产品序号"
                                width="300">
                                </el-table-column>
                                <el-table-column
                                prop="metering"
                                label="计量单位"
                                width="120">
                                </el-table-column>
                                <el-table-column
                                prop="money"
                                label="金额"
                                width="120">
                                </el-table-column>
                                <el-table-column
                                prop="company"
                                label="使用公司"
                                width="120">
                                </el-table-column>
                                <!-- <el-table-column
                                fixed="right"
                                label="操作"
                                width="100">
                                <template slot-scope="scope">
                                    <el-button type="text" size="small" @click="viewassetsf(scope.row)">查看</el-button>
                                    <el-button type="text" size="small"  @click="editorzcf(scope.row)">编辑</el-button>
                                </template>
                                </el-table-column> -->
                            </el-table>
                            <!-- 表格展示结束 -->
                            <!-- 分页展示 -->
                            <div class="block" style="margin-top:20px;text-align:left;">
                                <el-pagination
                                @size-change="handleSizeChange"
                                @current-change="handleCurrentChange"
                                :current-page.sync="currentPage2"
                                :page-sizes="[5, 10, 20, 30]"
                                :page-size="5"
                                layout="sizes, prev, pager, next"
                                :total="tableData.length">
                                </el-pagination>
                            </div>
                            <!-- 分页展示结束 -->
                        </el-tab-pane>
                    </el-tabs>
    </div>
</template>
<script>
export default {
    data(){
        return {
            innerVisible: false,
            activeName: 'first',
            tableData: [{
            "id":1,
            "bar_code":"03010001",
            "name":"打印机",
            "type_id":"02",
            "specification":"索尼3000",
            "sn":49090343,
            "metering":"台",
            "money":2980,
            "company":"光威",
            "department":"",
            "purchase_time":"2018-06-08",
            "user_id":1001,
            "manager_id":102,
            "address":"办公室北区",
            "duration_use":"",
            "source":"购入",
            "remarks":"",
            "image":"http://placeholder.qiniudn.com/200x200",
            "supplier":"索尼赛格旗舰店",
            "contacts":"张素芳",
            "tell":13131312323,
            "expiry_time":"2019-06-08",
            "explain":""
        },
        {
            "id":2,
            "bar_code":"03010011",
            "name":"切纸机",
            "type_id":"03",
            "specification":"索尼3000",
            "sn":49090343,
            "metering":"台",
            "money":280,
            "company":"南京",
            "department":"",
            "purchase_time":"2018-06-07",
            "user_id":1001,
            "manager_id":102,
            "address":"办公室北区",
            "duration_use":"",
            "source":"购入",
            "remarks":"",
            "image":"http://placeholder.qiniudn.com/200x200",
            "supplier":"索尼赛格旗舰店",
            "contacts":"张素芳",
            "tell":13131312323,
            "expiry_time":"2019-06-08",
            "explain":""
        },
        {
            "id":3,
            "bar_code":"03010013",
            "name":"复印机",
            "type_id":"03",
            "specification":"索尼3000",
            "sn":49090343,
            "metering":"台",
            "money":280,
            "company":"南京",
            "department":"",
            "purchase_time":"2018-06-07",
            "user_id":1001,
            "manager_id":102,
            "address":"办公室北区",
            "duration_use":"",
            "source":"购入",
            "remarks":"",
            "image":"http://placeholder.qiniudn.com/200x200",
            "supplier":"索尼赛格旗舰店",
            "contacts":"张素芳",
            "tell":13131312323,
            "expiry_time":"2019-06-08",
            "explain":""
        },
        {
            "id":4,
            "bar_code":"03010031",
            "name":"电风扇",
            "type_id":"03",
            "specification":"索尼3000",
            "sn":49090343,
            "metering":"台",
            "money":280,
            "company":"南京",
            "department":"",
            "purchase_time":"2018-06-07",
            "user_id":1001,
            "manager_id":102,
            "address":"办公室北区",
            "duration_use":"",
            "source":"购入",
            "remarks":"",
            "image":"http://placeholder.qiniudn.com/200x200",
            "supplier":"索尼赛格旗舰店",
            "contacts":"张素芳",
            "tell":13131312323,
            "expiry_time":"2019-06-08",
            "explain":""
        },
        {
            "id":5,
            "bar_code":"03010031",
            "name":"电风扇",
            "type_id":"03",
            "specification":"索尼3000",
            "sn":49090343,
            "metering":"台",
            "money":280,
            "company":"南京",
            "department":"",
            "purchase_time":"2018-06-07",
            "user_id":1001,
            "manager_id":102,
            "address":"办公室北区",
            "duration_use":"12",
            "source":"购入",
            "remarks":"",
            "image":"http://placeholder.qiniudn.com/200x200",
            "supplier":"索尼赛格旗舰店",
            "contacts":"张素芳",
            "tell":13131312323,
            "expiry_time":"2019-06-08",
            "explain":""
        },
        {
            "id":6,
            "bar_code":"03010031",
            "name":"电风扇",
            "type_id":"03",
            "specification":"索尼3000",
            "sn":49090343,
            "metering":"台",
            "money":280,
            "company":"南京",
            "department":"",
            "purchase_time":"2018-06-07",
            "user_id":1001,
            "manager_id":102,
            "address":"办公室北区",
            "duration_use":"10",
            "source":"购入",
            "remarks":"",
            "image":"http://placeholder.qiniudn.com/200x200",
            "supplier":"索尼赛格旗舰店",
            "contacts":"张素芳",
            "tell":13131312323,
            "expiry_time":"2019-06-08",
            "explain":""
        },
        {
            "id":7,
            "bar_code":"03010031",
            "name":"电风扇",
            "type_id":"03",
            "specification":"索尼3000",
            "sn":49090343,
            "metering":"台",
            "money":280,
            "company":"南京",
            "department":"",
            "purchase_time":"2018-06-07",
            "user_id":1001,
            "manager_id":102,
            "address":"办公室北区",
            "duration_use":"",
            "source":"购入",
            "remarks":"",
            "image":"http://placeholder.qiniudn.com/200x200",
            "supplier":"索尼赛格旗舰店",
            "contacts":"张素芳",
            "tell":13131312323,
            "expiry_time":"2019-06-08",
            "explain":""
        },
        {
            "id":8,
            "bar_code":"03010031",
            "name":"电风扇",
            "type_id":"03",
            "specification":"索尼3000",
            "sn":49090343,
            "metering":"台",
            "money":280,
            "company":"南京",
            "department":"",
            "purchase_time":"2018-06-07",
            "user_id":1001,
            "manager_id":102,
            "address":"办公室北区",
            "duration_use":"",
            "source":"购入",
            "remarks":"",
            "image":"http://placeholder.qiniudn.com/200x200",
            "supplier":"索尼赛格旗舰店",
            "contacts":"张素芳",
            "tell":13131312323,
            "expiry_time":"2019-06-08",
            "explain":""
        },
        {
            "id":9,
            "bar_code":"03010031",
            "name":"电风扇",
            "type_id":"03",
            "specification":"索尼3000",
            "sn":49090343,
            "metering":"台",
            "money":280,
            "company":"南京",
            "department":"",
            "purchase_time":"2018-06-07",
            "user_id":1001,
            "manager_id":102,
            "address":"办公室北区",
            "duration_use":"",
            "source":"购入",
            "remarks":"",
            "image":"http://placeholder.qiniudn.com/200x200",
            "supplier":"索尼赛格旗舰店",
            "contacts":"张素芳",
            "tell":13131312323,
            "expiry_time":"2019-06-08",
            "explain":""
        },
        {
            "id":10,
            "bar_code":"03010031",
            "name":"电风扇",
            "type_id":"03",
            "specification":"索尼3000",
            "sn":49090343,
            "metering":"台",
            "money":280,
            "company":"南京",
            "department":"",
            "purchase_time":"2018-06-07",
            "user_id":1001,
            "manager_id":102,
            "address":"办公室北区",
            "duration_use":"",
            "source":"购入",
            "remarks":"",
            "image":"http://placeholder.qiniudn.com/200x200",
            "supplier":"索尼赛格旗舰店",
            "contacts":"张素芳",
            "tell":13131312323,
            "expiry_time":"2019-06-08",
            "explain":""
        },
        {
            "id":11,
            "bar_code":"03010031",
            "name":"电风扇",
            "type_id":"03",
            "specification":"索尼3000",
            "sn":49090343,
            "metering":"台",
            "money":280,
            "company":"南京",
            "department":"",
            "purchase_time":"2018-06-07",
            "user_id":1001,
            "manager_id":102,
            "address":"办公室北区",
            "duration_use":"",
            "source":"购入",
            "remarks":"",
            "image":"http://placeholder.qiniudn.com/200x200",
            "supplier":"索尼赛格旗舰店",
            "contacts":"张素芳",
            "tell":13131312323,
            "expiry_time":"2019-06-08",
            "explain":""
        }],
        multipleSelection: []
        }
    }
}
</script>

